language: node_js
matrix:
  include:
  - node_js: 4
  - node_js: 6
  - node_js: 7
  allow_failures:
  - node_js: 8
  - node_js: stable
install:
 - npm install
 - for i in {gulp,grunt,fly,brunch}; do npm install; done
script: benchmark.sh